import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import { brand, contextOptions, maturityScale, questions, sponsorCopy } from './config'
import { enrichResult, scoreAnswers } from './scoring'
import { buildPayload, submitLead } from './leadSink'
import { clearState, loadState, saveState } from './storage'
import { track } from './analytics'
import type { AssessmentState, Answer, ContextData, ContactData, Screen } from './types'

const emptyContext: ContextData = { vertical: '', exitHorizon: '', serviceTitanUser: '' }
const emptyContact: ContactData = { firstName: '', lastName: '', workEmail: '', firm: '', role: '', phone: '', companyAlias: '' }
const initialState = (): AssessmentState => { const params = new URLSearchParams(location.search); return { screen: 'landing', questionIndex: 0, answers: {}, context: { ...emptyContext }, contact: { ...emptyContact }, attribution: { source: params.get('source') ?? 'qr', host: params.get('host') ?? 'pantheon', campaign: params.get('campaign') ?? 'exit-readiness' }, submitted: false } }

function App() {
  const [state, setState] = useState<AssessmentState>(() => loadState() ?? initialState())
  const [error, setError] = useState('')
  const [shareCopied, setShareCopied] = useState(false)
  const result = useMemo(() => enrichResult(scoreAnswers(state.answers), state.context), [state.answers, state.context])
  useEffect(() => saveState(state), [state])
  useEffect(() => { track('assessment_started', { source: state.attribution.source }) }, [])
  const update = (patch: Partial<AssessmentState>) => setState((current) => ({ ...current, ...patch }))
  const go = (screen: Screen) => { setError(''); update({ screen }); track(`screen_${screen}`) }
  const answer = (value: Answer) => { setError(''); update({ answers: { ...state.answers, [questions[state.questionIndex].id]: value } }) }
  const reset = () => { clearState(); setState(initialState()); setError(''); track('assessment_restarted') }
  const submit = async () => { setError(''); try { const payload = buildPayload(state, result); const response = await submitLead(payload); update({ submitted: true, submissionId: response.submissionId, screen: 'immediate-result' }); track('lead_submitted') } catch (e) { setError(e instanceof Error ? e.message : 'Submission failed. Please retry.') } }
  const copyShare = async () => { try { await navigator.clipboard.writeText(`${location.origin}${location.pathname}`); setShareCopied(true); track('share_clicked'); setTimeout(() => setShareCopied(false), 1800) } catch { setError('Copy is unavailable in this browser.') } }
  const currentQuestion = questions[state.questionIndex]
  return <div className="app-shell"><Header onReset={reset} /><main>
    {state.screen === 'landing' && <Landing onStart={() => go('buyer-context')} />}
    {state.screen === 'buyer-context' && <BuyerContext onContinue={() => go('context')} />}
    {state.screen === 'context' && <ContextForm context={state.context} onChange={(context) => update({ context })} onBack={() => go('buyer-context')} onContinue={() => go('assessment')} />}
    {state.screen === 'assessment' && currentQuestion && <Assessment index={state.questionIndex} answers={state.answers} onAnswer={answer} onBack={() => state.questionIndex ? update({ questionIndex: state.questionIndex - 1 }) : go('context')} onContinue={() => state.answers[currentQuestion.id] === undefined ? setError('Choose a number from 1 to 5 to continue.') : state.questionIndex < questions.length - 1 ? update({ questionIndex: state.questionIndex + 1 }) : go('lead')} error={error} />}
    {state.screen === 'lead' && <LeadForm contact={state.contact} onChange={(contact) => update({ contact })} onBack={() => state.questionIndex ? update({ screen: 'assessment', questionIndex: questions.length - 1 }) : go('context')} onSubmit={submit} error={error} />}
    {state.screen === 'immediate-result' && <ImmediateResult result={result} onContinue={() => go('detail')} />}
    {state.screen === 'detail' && <DetailedResult result={result} onContinue={() => go('conversion')} />}
    {state.screen === 'conversion' && <Conversion result={result} copyShare={copyShare} shareCopied={shareCopied} onRestart={reset} />}
  </main><Footer /></div>
}

function Header({ onReset }: { onReset: () => void }) { return <header className="site-header"><div className="brand-lockup" aria-label="ServiceTitan, Piper Sandler, and West Monroe"><img className="brand-logo servicetitan-logo" src="/brand/servicetitan.png" alt="ServiceTitan" /><span className="plus">+</span><img className="brand-logo piper-logo" src="/brand/piper-sandler.png" alt="Piper Sandler" /><span className="plus">+</span><img className="brand-logo west-monroe-logo" src="/brand/west-monroe.png" alt="West Monroe" /></div><button className="text-button" onClick={onReset}>Start over</button></header> }
function Footer() { return <footer><span>{brand.event}</span><span>Directional self-assessment · <a href={sponsorCopy.privacyUrl}>Privacy</a></span></footer> }
function Shell({ children, kicker, title, intro }: { children: React.ReactNode; kicker?: string; title: string; intro?: string }) { return <section className="page"><div className="kicker">{kicker ?? brand.eyebrow}</div><h1>{title}</h1>{intro && <p className="lede">{intro}</p>}{children}</section> }
function Landing({ onStart }: { onStart: () => void }) { return <Shell title={brand.title} intro="A two-minute pulse for commercial and residential services platforms. See what the portfolio company can defend today, where a buyer may press, and where the next increment of value could be created."><div className="hero-grid"><div><div className="signal-line"><span className="signal-dot" /> Three buyer tests <span className="slash">/</span> Four questions <span className="slash">/</span> One useful conversation</div><div className="test-grid">{[['01', 'Scalable platform'], ['02', 'Trusted data'], ['03', 'Operationalized AI']].map(([num, label]) => <div className="test-card" key={num}><small>{num}</small><strong>{label}</strong></div>)}</div></div><aside className="hero-aside"><p>Built for the Pantheon happy hour.</p><p className="aside-quote">Useful before it feels commercial.</p></aside></div><button className="primary-button" onClick={onStart}>Start the readiness pulse <span>→</span></button><p className="microcopy">No exact financial information required. The result is directional and based on self-reported information.</p></Shell> }
function BuyerContext({ onContinue }: { onContinue: () => void }) { return <Shell kicker="The buyer lens" title="What a strong portfolio company can prove" intro="Buyers increasingly expect portfolio companies to demonstrate that the operating platform can scale, the data is reliable, AI creates measurable value, and leadership can defend the technology-enabled value story."><div className="buyer-list">{[['01', 'The platform scales', 'New locations and acquisitions do not compound complexity.'], ['02', 'The data can be trusted', 'KPIs reconcile quickly and explain what drives performance.'], ['03', 'AI creates measurable value', 'Capabilities are embedded in workflows, not just on a roadmap.'], ['04', 'Leadership can defend the story', 'The evidence connects investment to realized and remaining value.']].map(([n, t, d]) => <div className="buyer-row" key={n}><span>{n}</span><div><strong>{t}</strong><p>{d}</p></div></div>)}</div><button className="primary-button" onClick={onContinue}>Tell us about the portfolio company <span>→</span></button></Shell> }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (v: string) => void }) { return <label className="field"><span>{label}<em>*</em></span><select value={value} onChange={(e) => onChange(e.target.value)}><option value="">Select one</option>{options.map((o) => <option key={o}>{o}</option>)}</select></label> }
function ContextForm({ context, onChange, onBack, onContinue }: { context: ContextData; onChange: (c: ContextData) => void; onBack: () => void; onContinue: () => void }) { const set = (key: keyof ContextData, value: string) => onChange({ ...context, [key]: value }); const valid = Boolean(context.vertical && context.exitHorizon && context.serviceTitanUser); return <Shell kicker="Portfolio company context" title="Tell us about the portfolio company" intro="Three quick details help tailor the examples and follow-up path. They do not change the maturity score."><div className="form-grid"><SelectField label="Industry vertical" value={context.vertical} options={contextOptions.vertical} onChange={(v) => set('vertical', v)} /><SelectField label="Expected exit horizon" value={context.exitHorizon} options={contextOptions.exitHorizon} onChange={(v) => set('exitHorizon', v)} /><SelectField label="ServiceTitan user" value={context.serviceTitanUser} options={contextOptions.serviceTitanUser} onChange={(v) => set('serviceTitanUser', v)} /></div><div className="button-row"><button className="secondary-button" onClick={onBack}>← Back</button><button className="primary-button" disabled={!valid} onClick={onContinue}>Start four questions <span>→</span></button></div></Shell> }
function Progress({ index }: { index: number }) { return <div className="progress-wrap"><div className="progress-meta"><span>Readiness pulse</span><span>{index} of {questions.length}</span></div><div className="progress-track"><div style={{ width: `${(index / questions.length) * 100}%` }} /></div></div> }
function Assessment({ index, answers, onAnswer, onBack, onContinue, error }: { index: number; answers: AssessmentState['answers']; onAnswer: (v: Answer) => void; onBack: () => void; onContinue: () => void; error: string }) { const q = questions[index]; const dimension = dimensionsLabel(q.dimension); return <Shell kicker={`Question ${index + 1} · ${dimension}`} title={q.prompt} intro={q.example}><Progress index={index + 1} /><div className="buyer-lens"><span>Buyer may test</span>{q.buyerLens}</div><div className="maturity-instruction"><strong>Which description most closely represents your current state?</strong><span>Select one maturity level from 1 to 5.</span></div><div className="scale-header"><span>1 · {q.scaleMin}</span><span>5 · {q.scaleMax}</span></div><div className="maturity-options">{maturityScale.map((item) => <button aria-label={`${item.value}, ${item.label}: ${q.maturityDescriptions[item.value]}`} className={`maturity-option ${answers[q.id] === item.value ? 'selected' : ''}`} key={item.value} onClick={() => onAnswer(item.value)}><span className="score-badge">{item.value}</span><div className="maturity-copy"><strong>{item.label}</strong><small>{q.maturityDescriptions[item.value]}</small></div>{answers[q.id] === item.value && <span className="check">✓</span>}</button>)}</div>{error && <p className="error" role="alert">{error}</p>}<div className="button-row"><button className="secondary-button" onClick={onBack}>← Back</button><button className="primary-button" onClick={onContinue}>{index === questions.length - 1 ? 'Continue to results' : 'Continue'} <span>→</span></button></div></Shell> }
function dimensionsLabel(key: string) { return ({ technology: 'Scalable platform', data: 'Trusted data', ai: 'Operationalized AI' } as Record<string, string>)[key] }
function maturityLevel(score: number) { return (1 + (score / 100) * 4).toFixed(1) }
function ScorePill({ score }: { score: number }) { return <span className="score-pill">Level {maturityLevel(score)}<small>/5</small></span> }
function ImmediateResult({ result, onContinue }: { result: ReturnType<typeof enrichResult>; onContinue: () => void }) { return <Shell kicker="Your readiness result" title={result.archetype.name} intro={result.archetype.strapline}><div className="result-top"><div className="result-mark">{result.archetype.name.split(' ').map((word) => word[0]).join('')}</div><div><p className="result-label">Overall maturity signal</p><div className="big-score">{maturityLevel(result.overall)}<span>/5</span></div></div></div><p className="result-description">{result.archetype.description}</p><div className="preview-grid"><div><span className="overline">What can be defended</span><strong>{[...result.dimensions].sort((a, b) => b.score - a.score)[0].label}</strong><p>One strength to bring into the next conversation.</p></div><div><span className="overline">Where buyers may press</span><strong>{result.buyerQuestions[0]}</strong><p>See the complete profile and action plan below.</p></div></div><div className="value-path"><span>West Monroe value opportunity</span><strong>{result.valuePath}</strong><p>{result.recommendedActions[0]}</p></div><button className="primary-button" onClick={onContinue}>See my complete profile <span>→</span></button></Shell> }
function LeadForm({ contact, onChange, onBack, onSubmit, error }: { contact: ContactData; onChange: (c: ContactData) => void; onBack: () => void; onSubmit: () => void; error: string }) { const set = (key: keyof ContactData, value: string) => onChange({ ...contact, [key]: value }); const valid = Boolean(contact.firstName && contact.lastName && /\S+@\S+\.\S+/.test(contact.workEmail) && contact.firm && contact.role); return <Shell kicker="Unlock your score" title="Enter your details to see your readiness score" intro="Your work email and contact information are required to reveal your score and complete profile."><div className="form-grid"><label className="field"><span>First name <em>*</em></span><input value={contact.firstName} onChange={(e) => set('firstName', e.target.value)} autoComplete="given-name" /></label><label className="field"><span>Last name <em>*</em></span><input value={contact.lastName} onChange={(e) => set('lastName', e.target.value)} autoComplete="family-name" /></label><label className="field full"><span>Work email <em>*</em></span><input type="email" value={contact.workEmail} onChange={(e) => set('workEmail', e.target.value)} autoComplete="email" placeholder="you@company.com" /></label><label className="field"><span>Firm or organization <em>*</em></span><input value={contact.firm} onChange={(e) => set('firm', e.target.value)} /></label><label className="field"><span>Role <em>*</em></span><input value={contact.role} onChange={(e) => set('role', e.target.value)} /></label><label className="field"><span>Phone <em>(optional)</em></span><input value={contact.phone} onChange={(e) => set('phone', e.target.value)} type="tel" /></label><label className="field"><span>Portfolio company or alias <em>(optional)</em></span><input value={contact.companyAlias} onChange={(e) => set('companyAlias', e.target.value)} /></label></div>{error && <p className="error" role="alert">{error}</p>}<div className="button-row"><button className="secondary-button" onClick={onBack}>← Back</button><button className="primary-button" disabled={!valid} onClick={onSubmit}>Show my readiness score <span>→</span></button></div><p className="microcopy">Privacy details and final sponsor language are placeholders pending approval.</p></Shell> }
function DetailedResult({ result, onContinue }: { result: ReturnType<typeof enrichResult>; onContinue: () => void }) { return <Shell kicker="Your complete profile" title={result.archetype.name} intro={result.archetype.description}><div className="detail-heading"><div><span className="overline">Overall maturity signal</span><div className="big-score">{maturityLevel(result.overall)}<span>/5</span></div></div><span className="archetype-tag">{result.archetype.strapline}</span></div><div className="dimension-list">{result.dimensions.map((d) => <div className="dimension" key={d.key}><div className="dimension-head"><span><strong>{d.label}</strong><small>{d.description}</small></span><ScorePill score={d.score} /></div><div className="bar"><div style={{ width: `${d.score}%` }} /></div></div>)}</div><div className="two-col"><div><h2>What can be defended</h2><ul>{result.strengths.map((x) => <li key={x}>{x}</li>)}</ul><h2>What a buyer may test</h2><ul>{result.buyerQuestions.map((x) => <li key={x}>{x}</li>)}</ul></div><div><h2>Where incremental value remains</h2><p className="value-title">{result.valuePath}</p><ul>{result.recommendedActions.map((x) => <li key={x}>{x}</li>)}</ul><h2>Qualifiers</h2><div className="chips">{(result.qualifiers.length ? result.qualifiers : ['No additional qualifiers']).map((x) => <span key={x}>{x}</span>)}</div></div></div><button className="primary-button" onClick={onContinue}>Choose a next step <span>→</span></button></Shell> }
function Conversion({ result, copyShare, shareCopied, onRestart }: { result: ReturnType<typeof enrichResult>; copyShare: () => void; shareCopied: boolean; onRestart: () => void }) { return <Shell kicker="Next conversation" title="Turn the signal into a useful next step" intro={`Your ${result.archetype.name} profile points to ${result.valuePath.toLowerCase()}. Choose the conversation that would be most useful now.`}><div className="conversion-grid"><button className="conversion-card" onClick={() => window.location.href = `mailto:?subject=Exit readiness discussion&body=I received a ${result.archetype.name} result and would like to discuss next steps.`}><span>01</span><strong>Talk to the team</strong><p>Start a conversation about the opportunity signal and urgency.</p><b>→</b></button><button className="conversion-card" onClick={copyShare}><span>02</span><strong>{shareCopied ? 'Link copied' : 'Share the pulse'}</strong><p>Share the assessment entry point with a colleague. No result data is included.</p><b>→</b></button><button className="conversion-card" onClick={onRestart}><span>03</span><strong>Run it again</strong><p>Test another business profile or revisit your answers.</p><b>→</b></button></div><p className="microcopy">Named sponsor contacts and final follow-up links will be added after approval.</p></Shell> }

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
